# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7dc74bb29847a6fce6fb56ffdc4eb6f87d30ecea83c2d79cca3cfbf56876e8145840ed91865374f77ea0d3bf9bb787bf45a9603f25c9418fac1af2d4dfcbd462

test:
  secret_key_base: 95bc407ba4d8143233f4a5f84865c3403389d7a794e1eff768cd85f17a4b7fa8694076fe7e2e8f2091ab34537940155cf182bc4bc738532ef730358fa08d9457

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
